# Generated by Django 5.2 on 2025-04-19 08:36

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                default="profile_images/default.png",
                upload_to=users.models.user_profile_image_path,
            ),
        ),
    ]
